from . import (
    alacritty,
    apps,
    bash,
    colors,
    dunst,
    fastfetch,
    fish,
    global_settings,
    gtk,
    hyprland,
    i3,
    kitty,
    nvim,
    okular,
    picom,
    polybar,
    qt,
    rofi,
    sioyek,
    tmux,
    wallpaper,
    waybar,
    yazi,
    zsh,
)

modules = {
    "alacritty": alacritty.parse_alacritty,
    "apps": apps.parse_apps,
    "bash": bash.parse_bash,
    "colors": colors.parse_colors,
    "dunst": dunst.parse_dunst,
    "fastfetch": fastfetch.parse_fastfetch,
    "fish": fish.parse_fish,
    "global": global_settings.parse_global,
    "gtk": gtk.parse_gtk,
    "hyprland": hyprland.parse_hyprland,
    "i3": i3.parse_i3,
    "kitty": kitty.parse_kitty,
    "nvim": nvim.parse_nvim,
    "okular": okular.parse_okular,
    "picom": picom.parse_picom,
    "polybar": polybar.parse_polybar,
    "qt": qt.parse_qt,
    "rofi": rofi.parse_rofi,
    "tmux": tmux.parse_tmux,
    "sioyek": sioyek.parse_sioyek,
    "wallpaper": wallpaper.parse_wallpaper,
    "waybar": waybar.parse_waybar,
    "yazi": yazi.parse_yazi,
    "zsh": zsh.parse_zsh,
}
