RICER_DEFAULT_CFG = "~/.config/ricer/ricer.yml"
RICER_DEFAULT_OVERRIDE = "~/.config/ricer/ricer-global.yml"
RICER_BEFORE_OVERRIDE = "~/.config/ricer/before-global.yml"
RICER_AFTER_OVERRIDE = "~/.config/ricer/after-global.yml"
RICER_DEFAULT_WALLPAPER_PATH = "~/Pictures/wallpapers"
RICER_DEFAULT_SCRIPTS_PATH = "~/Documents/git/dotfiles/user_scripts/"
